"""rename raw_name to test_name

Revision ID: 6ac66f3f43f2
Revises: 5b4d8ad0556c
Create Date: 2026-05-27 13:52:02.283732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac66f3f43f2'
down_revision: Union[str, None] = '5b4d8ad0556c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('test_name', sa.String(length=150), nullable=False))
    op.alter_column('test_results', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('test_results', 'raw_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('raw_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.alter_column('test_results', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('test_results', 'test_name')
    # ### end Alembic commands ###
